/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ChainOfThought,
  ChainOfThoughtInterface,
} from "../ChainOfThought";

const _abi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "test",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "pure",
  },
] as const;

export class ChainOfThought__factory {
  static readonly abi = _abi;
  static createInterface(): ChainOfThoughtInterface {
    return new Interface(_abi) as ChainOfThoughtInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ChainOfThought {
    return new Contract(address, _abi, runner) as unknown as ChainOfThought;
  }
}
